### ISSUE TITLE
Windows build with libprotobuf package

### ISSUE THREAD

**Issue by djsutherland** [conda-forge/onnx-feedstock#14]
Windows builds are temporarily disabled by #12. Example [failure](https://ci.appveyor.com/project/conda-forge/onnx-feedstock/build/1.0.35/job/cd3mi9lg7rherf18), which had lots of linking errors like

`
    onnx-ml.pb.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl google::protobuf::Message::SerializeWithCachedSizes(class google::protobuf::io::CodedOutputStream *)const " (?SerializeWithCachedSizes@Message@protobuf@google@@UEBAXPEAVCodedOutputStream@io@23@@Z)
`

Think this is caused by https://github.com/conda-forge/libprotobuf-feedstock/pull/2. If I can't get that PR working, will try patching to make onnx use the static libprotobuf on Windows.

**Comment by clouds56** [comment]
any updates?
